import dotenv from "dotenv";
import { Database, IdToken, Provider } from "ltijs";
import express from "express";
import { Request, Response } from "express";
import { setupSwagger } from "./docs/swagger.js";
import { assignmentRouter } from "./routes/assignment.routes.js";
import { login } from "./routes/auth.js";
import { courseRouter } from "./routes/course.routes.js";
import { userRouter } from "./routes/user.routes.js";

dotenv.config();

const lti = Provider;

const registerMoodlePlatform = async (): Promise<void> => {
  try {
    await lti.registerPlatform({
      url: process.env.MOODLE_URL, // e.g., 'https://your-moodle-domain.com'
      name: "Main Moodle Platform",
      clientId: process.env.MOODLE_CLIENT_ID, // Generated by Moodle when configuring the tool
      authenticationEndpoint: `${process.env.MOODLE_URL}/mod/lti/auth.php`,
      accesstokenEndpoint: `${process.env.MOODLE_URL}/mod/lti/token.php`,
      authConfig: {
        method: "JWK_SET",
        key: `${process.env.MOODLE_URL}/mod/lti/certs.php`, // Moodle's public key endpoint
      },
    });
    console.log(
      "✅ Moodle platform targets successfully mounted to provider registration context.",
    );
  } catch (err) {
    const error = err as Error;
    console.error("Error auto-registering Moodle Platform:", error.message);
  }
};

export const boostrapLti = async (db: Database): Promise<void> => {
  lti.setup(
    process.env.LTI_ENCRYPTION_KEY, // Secret key used to encrypt cookie data
    {
      plugin: db, // Tell ltijs to use the Sequelize plugin
    },
    {
      // Configure default routes that ltijs will automatically generate for you
      appRoute: "/launch", // The LTI Launch URL (Target Link URI)
      loginRoute: "/login", // The OIDC Login Initiation URL
      keysetRoute: "/keys", // The JWKS URL (Public Keys)
      cookies: {
        secure: false, // Must be false for HTTP localhost
        sameSite: "Lax", // Must be Lax or Strict if secure is false
      },
      devMode: true,
      cors: true,
    },
  );

  lti.whitelist(
    "/api-docs",
    "/api-docs/",
    "/api-docs.json",
    "/api-docs/swagger-ui.css",
    "/api-docs/swagger-ui-bundle.js",
    "/api-docs/swagger-ui-standalone-preset.js",
    "/api-docs/swagger-ui-init.js",
    "/api-docs/favicon-32x32.png",
    "/api-docs/favicon-16x16.png",
  );
  lti.onConnect(login);

  // server.js (Your Express Backend)

  // 1. The Deep Linking Launch
  lti.onDeepLinking((token: IdToken, req: Request, res: Response) => {
    // Redirect the user to your Next.js page.
    // res.locals.ltik is a secure token generated by ltijs to maintain the session.
    const createPageUrl = `http://localhost:5173?ltik=${res.locals.ltik}`;

    return lti.redirect(res, createPageUrl);
  });

  lti.app.use(express.json());
  setupSwagger(lti.app);
  lti.app.use("/api", assignmentRouter);
  lti.app.use("/api", courseRouter);
  lti.app.use("/api", userRouter);

  /**
   * @openapi
   * /generate-deeplink:
   *   post:
   *     tags: [LTI]
   *     summary: Generate an LTI deep-link response
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             type: object
   *             required: [taskTitle, maxScore, taskId]
   *             properties:
   *               taskTitle:
   *                 type: string
   *               maxScore:
   *                 type: number
   *                 exclusiveMinimum: 0
   *               taskId:
   *                 type: string
   *     responses:
   *       200:
   *         description: HTML form that submits the deep-link response
   *         content:
   *           text/html:
   *             schema:
   *               type: string
   *       401:
   *         description: Missing LTI session
   *       500:
   *         description: Server error
   */
  lti.app.post("/api/generate-deeplink", async (req, res) => {
    try {
      const { taskTitle, maxScore, taskId } = req.body;

      if (!res.locals.token) {
        return res.status(401).send("Unauthorized: Missing LTI session");
      }

      const contentItems = [
        {
          type: "ltiResourceLink",
          title: taskTitle,
          custom: {
            // הנתון הזה (taskId) יישמר במודל ויישלח אלינו חזרה כשהסטודנט ילחץ!
            taskId: taskId,
          },
          lineItem: {
            scoreMaximum: Number(maxScore),
            label: `${taskTitle} Grade`,
          },
        },
      ];

      const formHtml = await lti.DeepLinking.createDeepLinkingForm(
        res.locals.token,
        contentItems,
        { message: "המטלה נוצרה וצורפה לקורס בהצלחה!" },
      );

      return res.send(formHtml);
    } catch (error) {
      console.error("Error generating deep link:", error);
      return res.status(500).send("Error generating deep link");
    }
  });

  await lti.deploy({ port: process.env.PORT || 3001 });
  console.log(
    `🚀 LTI Tool Provider Engine live on port ${process.env.PORT || 3001}`,
  );

  // Register the Moodle Platform dynamically or keep it in your code config
  await registerMoodlePlatform();
};
