import dotenv from "dotenv";
import { Database, IdToken, Provider } from "ltijs";
import express from "express";
import { Request, Response } from "express";
import { LtiToken } from "./common/types/lti.js";
import { setupSwagger } from "./docs/swagger.js";
import { appealRouter } from "./routes/appeal.routes.js";
import { UserRole } from "./entities/enums.js";
import { AssignmentRepository } from "./repositories/assignment.repository.js";
import { assignmentRouter } from "./routes/assignment.routes.js";
import { login } from "./routes/auth.js";
import { courseRouter } from "./routes/course.routes.js";
import { questionRouter } from "./routes/question.routes.js";
import { submissionRouter } from "./routes/submission.routes.js";
import { messageRouter } from "./routes/message.routes.js";
import { notificationRouter } from "./routes/notification.routes.js";
import { userRouter } from "./routes/user.routes.js";
import {
  LtiLaunchDataError,
  LtiLaunchSyncService,
  LtiRoleConflictError,
} from "./services/lti-launch-sync.service.js";
import { gradingWorker } from "./workers/grading.worker.js";
import { handleUploadErrors } from "./middleware/upload.js";

dotenv.config();

const lti = Provider;
const ltiLaunchSyncService = new LtiLaunchSyncService();
const assignmentRepository = new AssignmentRepository();

const registerMoodlePlatform = async (): Promise<void> => {
  try {
    await lti.registerPlatform({
      url: process.env.MOODLE_URL, // e.g., 'https://your-moodle-domain.com'
      name: "Main Moodle Platform",
      clientId: process.env.MOODLE_CLIENT_ID, // Generated by Moodle when configuring the tool
      authenticationEndpoint: `${process.env.MOODLE_URL}/mod/lti/auth.php`,
      accesstokenEndpoint: `${process.env.MOODLE_URL}/mod/lti/token.php`,
      authConfig: {
        method: "JWK_SET",
        key: `${process.env.MOODLE_URL}/mod/lti/certs.php`, // Moodle's public key endpoint
      },
    });
    console.log(
      "✅ Moodle platform targets successfully mounted to provider registration context.",
    );
  } catch (err) {
    const error = err as Error;
    console.error("Error auto-registering Moodle Platform:", error.message);
  }
};

const handleDeepLinkingLaunch = async (
  token: IdToken,
  res: Response,
): Promise<void> => {
  try {
    const synchronized = await ltiLaunchSyncService.synchronize(
      token as LtiToken,
    );
    const createPageUrl = new URL(
      `${process.env.FRONTEND_URL}/courses/${synchronized.courseId}/assignments/new`,
    );

    createPageUrl.searchParams.set("ltik", res.locals.ltik);
    createPageUrl.searchParams.set("userId", synchronized.userId);
    lti.redirect(res, createPageUrl.toString());
  } catch (error) {
    if (error instanceof LtiRoleConflictError) {
      res.status(403).send("Moodle role conflicts with the stored global role");
      return;
    }

    if (error instanceof LtiLaunchDataError) {
      res.status(400).send(error.message);
      return;
    }

    console.error("Failed to synchronize deep-linking launch:", error);
    res.status(500).send("Failed to synchronize Moodle launch");
  }
};

export const boostrapLti = async (db: Database): Promise<void> => {
  lti.setup(
    process.env.LTI_ENCRYPTION_KEY, // Secret key used to encrypt cookie data
    {
      plugin: db, // Tell ltijs to use the Sequelize plugin
    },
    {
      // Configure default routes that ltijs will automatically generate for you
      appRoute: "/launch", // The LTI Launch URL (Target Link URI)
      loginRoute: "/login", // The OIDC Login Initiation URL
      keysetRoute: "/keys", // The JWKS URL (Public Keys)
      cookies: {
        secure: false, // Must be false for HTTP localhost
        sameSite: "Lax", // Must be Lax or Strict if secure is false
      },
      devMode: true,
      cors: true,
    },
  );

  lti.whitelist(
    { route: new RegExp(/^\/api\/.*/), method: "ALL" },
    "/api-docs",
    "/api-docs/",
    "/api-docs.json",
    "/api-docs/swagger-ui.css",
    "/api-docs/swagger-ui-bundle.js",
    "/api-docs/swagger-ui-standalone-preset.js",
    "/api-docs/swagger-ui-init.js",
    "/api-docs/favicon-32x32.png",
    "/api-docs/favicon-16x16.png",
  );
  lti.onConnect((token, req, res) => {
    void login(token, req, res);
  });

  // server.js (Your Express Backend)

  // 1. The Deep Linking Launch
  lti.onDeepLinking((token: IdToken, _req: Request, res: Response) => {
    void handleDeepLinkingLaunch(token, res);
  });

  lti.app.use(express.json());
  setupSwagger(lti.app);
  lti.app.use("/api", appealRouter);
  lti.app.use("/api", assignmentRouter);
  lti.app.use("/api", courseRouter);
  lti.app.use("/api", messageRouter);
  lti.app.use("/api", notificationRouter);
  lti.app.use("/api", userRouter);
  lti.app.use("/api", questionRouter);
  lti.app.use("/api", submissionRouter);
  lti.app.use(handleUploadErrors);

  /**
   * @openapi
   * /generate-deeplink:
   *   post:
   *     tags: [LTI]
   *     summary: Generate an LTI deep-link response
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             type: object
   *             required: [taskId]
   *             properties:
   *               taskId:
   *                 type: string
   *                 format: uuid
   *     responses:
   *       200:
   *         description: HTML form that submits the deep-link response
   *         content:
   *           text/html:
   *             schema:
   *               type: string
   *       401:
   *         description: Missing LTI session
   *       403:
   *         description: Lecturer role required
   *       404:
   *         description: Assignment not found in the launched course
   *       500:
   *         description: Server error
   */
  lti.app.post("/api/generate-deeplink", async (req, res) => {
    try {
      const { taskId } = req.body;

      if (!res.locals.token) {
        return res.status(401).send("Unauthorized: Missing LTI session");
      }

      const synchronized = await ltiLaunchSyncService.synchronize(
        res.locals.token as LtiToken,
      );

      if (synchronized.role !== UserRole.LECTURER) {
        return res.status(403).send("Only lecturers can create deep links");
      }

      const assignment =
        typeof taskId === "string"
          ? await assignmentRepository.findAssignmentById(taskId)
          : null;

      if (!assignment || assignment.courseId !== synchronized.courseId) {
        return res
          .status(404)
          .send("Assignment not found in the launched Moodle course");
      }

      const contentItems = [
        {
          type: "ltiResourceLink",
          title: assignment.name,
          custom: {
            taskId: assignment.id,
          },
          lineItem: {
            scoreMaximum: assignment.maxScore,
            label: `${assignment.name} Grade`,
          },
        },
      ];

      const formHtml = await lti.DeepLinking.createDeepLinkingForm(
        res.locals.token,
        contentItems,
        { message: "המטלה נוצרה וצורפה לקורס בהצלחה!" },
      );

      return res.send(formHtml);
    } catch (error) {
      console.error("Error generating deep link:", error);
      return res.status(500).send("Error generating deep link");
    }
  });

  await lti.deploy({ port: process.env.PORT || 3001 });
  console.log(
    `🚀 LTI Tool Provider Engine live on port ${process.env.PORT || 3001}`,
  );

  gradingWorker.start();

  const shutdown = async (): Promise<void> => {
    await gradingWorker.stop();
  };

  process.once("SIGINT", () => {
    void shutdown().finally(() => process.exit(0));
  });
  process.once("SIGTERM", () => {
    void shutdown().finally(() => process.exit(0));
  });

  // Register the Moodle Platform dynamically or keep it in your code config
  await registerMoodlePlatform();
};
